### ISSUE TITLE
runLocalState doesn't implement thread local state

### ISSUE THREAD

**Issue by arybczak** [re-xyr/cleff#1]
Because the only difference between `runLocalState` and `runSharedState` is that it uses `IORef` instead of `MVar`, so once you share the environment between threads, your local state becomes shared state prone to data races.

Same for `runLocalWriter`.

This is why `effectful` uses mutable, thread-local environment and stores data inside it directly :slightly_smiling_face:

**Comment by re-xyr** [comment]
I actually am very unclear about multithread programming. What is the difference in semantics between running two `State.Local` on separate threads versus running one `State.Shared`?

**Comment by re-xyr** [comment]
Maybe the name is also a bit misleading, it would be better to rename them to `readIORefState`, `readMVarState` etc.

**Comment by re-xyr** [comment]
Closing because

1. There isn't any confusion with naming now
2. Implementing thread-local state is not a priority. If I can see a way to implement it I will open another issue to track that.
