### ISSUE TITLE
Improvements to generation of operations via TH

### ISSUE THREAD

**Issue by arybczak** [re-xyr/cleff#12]
Hey,

I took your TH generation code and improved it in https://github.com/haskell-effectful/effectful/pull/60. Feel free to adapt it and/or see if it breaks for something I didn't anticipate :slightly_smiling_face:

**Comment by re-xyr** [comment]
Thanks for the improvement - I've left some comments there and added support for constructors using `Eff es` instead of `m` for cleff.

**Comment by re-xyr** [comment]
Fixed by 096ba95
