### ISSUE TITLE
Outline static effects

### ISSUE THREAD

**Issue by re-xyr** [re-xyr/cleff#4]
For any effect `e`, one can define instances for

```haskell
class Static e where
  type StaticEnv e :: Type
  -- Only env access & IO is possible
  staticInterpret :: (StaticIO, S e :> es) => e (Eff es) ~> Eff es
```

where

```haskell
data S e :: Effect where
  GetEnv :: Static e => S e m (StaticEnv e)
```

When `S e` is on the effect stack, operations can be performed.

```Haskell
instStaticIO :: (StaticIO => a) -> a

staticSend :: S e :> es => e (Eff es) ~> Eff es
staticSend e = instStaticIO $ staticInterpret e
```

The static effect `S e` is run by 

```haskell
staticHandler :: Static e => StaticEnv e -> Handler e es' es
staticHandler s GetEnv = pure s

runStatic :: Static e => StaticEnv e -> Eff (S e : es) ~> Eff es
runStatic s = interpret $ staticHandler s
-- Warning: this environment is shared among threads.
```

A dynamic effect can be degraded to a static one:

```Haskell
degrade :: Static e => Eff (e : es) ~> Eff (S e : es)
degrade = reinterpret sendStatic
```

Example static implementations:

```Haskell
instance Static (Reader r) where
  type StaticEnv (Reader r) = r
  staticInterpret = \case
    Ask -> getEnv
    Local f m -> do
      r <- getEnv
      interpose @(S (Reader r)) (staticHandler $ f r) m
```

Problems:

- Is it meaningful to "tag" static interpretations so one effect can have multiple `Static` instances and users can choose which to perform? This seems evil to me.
- `S` leaks the static effect environment to the user.
- How much will the performance degradation be compared to using internal constructs directly?
- Nowhere imposes control of IO - all static effects are granted IO access and assumed to be morally pure.
- Environment is immutable and shared among threads. This makes it less efficient than `effectful`'s mutable & thread-local ones.
- Unable to create opaque alias for `S e`.

ping @arybczak for opinions

**Comment by arybczak** [comment]
Hmm, you want to enforce single interpretation by using a type class? Interesting idea :thinking: 

> S leaks the static effect environment to the user.

Yes, that's ugly. I had a similar issue for a while in the past when all effects were primitive in a sense and I wanted to have interpreted ones, they initially showed on the list as `I e` instead of `e`. I really didn't like it.

> Nowhere imposes control of IO - all static effects are granted IO access and assumed to be morally pure.

Yeah, it's not that different from using `unsafeEff` directly.

> Environment is immutable

That is the main problem. If the environment is immutable, every change of the `StaticEnv e` will be `O(n)`, which completely destroys performance.
