### ISSUE TITLE
Pre-release probing

### ISSUE THREAD

**Issue by re-xyr** [re-xyr/cleff#9]
Since the library is feature-complete, and with the fix of #5, I think it is more or less the time to cut a release. 

In the spirit of arybczak/effectful#1, I'd like to ask @isovector, @KingOfTheHomeless and @noughtmare to take a look at this library and offer your opinions and/or point out flaws. I have also talked with @arybczak and @lexi-lambda about `cleff` before and gained some valuable insights, but if you have anything else that you'd like to point out then please don't hesitate to do so.

Some tl;drs about `cleff`:

- Like `effectful`, it is implemented with `ReaderT IO`, but differs greatly in details which is reflected in the discussion in #2. In particular, 
  - `effectful` stores both handlers and states in thread-local mutable arrays.
  - `cleff` stores handlers in immutable arrays and states in `IORef`s which are shared among threads.
- Due to these differences, unlike `effectful`, `cleff` does not have static dispatch or thread-local state.
- `cleff` aims to have expressive interpretation API that supports higher-order effects. Currently the API expressibility is on par with that of `polysemy` and easier to use in my opinion (except that the final monad can only be `IO` due to the obvious restriction of the implementation).
- `cleff` solves the HO semantics problem that haunts `eff` (hasura/eff#12) though I'm not sure if that solution is portable to `eff` given it needs to support coroutines.

**Comment by isovector** [comment]
Looks cool, and congratulations on the release! I'm not going to have time to look at this though, unfortunately!
